<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class ApplicationForm extends Model
{
    protected $fillable = [
        'application_for',
        'position',
        'step',
        'faculty_department',
        'bank_draft_no','draft_date',
        'payable_at','ref_no',
        'ref_date','full_name',
        'gender','spouse_name',
        'nationality','dob',
        'email',
        'position_current_held',
        'mobile',
        'name_phd_thesis',
        'supervisor',        
        'position_currenty',
        'work_address',
        'permanent_address',
        'correspondence_address',
        'doctoral_degree',
        'doctoral_university',
        'doctoral_joining',
        'doctoral_award',
        'doctoral_grades',
        'master_degree',
        'master_university',
        'master_joining',
        'master_award',
        'master_grades',
        'bachelor_degree',
        'bachelor_university',
        'bachelor_joining',
        'bachelor_award',
        'bachelor_grades',
        'school_degree',
        'school_university',
        'school_joining',
        'school_award',
        'school_grades',
        'others_degree',
        'others_grades',
        'others_university',
        'others_award',
        'others_joining',
        'education',
        'doctoral_university',
        'courses_taught',
        'compulsory_courses',
        'optional_courses',
        'other_courses',
        'doctoral_degree',
        'number_books_edited',
        'number_books_authored',
        'number_research_publications',
        'number_book_chapters',
        'number_patents',
        'number_research_grants',
        'number_presentations',
        'publications',
        'employment_history',
        'application_fee',
        'birth_certification',
        'degrees',
        'latest_cv',
        'no_objection_certificate',
        'recent_passport',
        'joining_date',
        'consider_lower_position',
        'other_information',
        'sau_reasons',
        'legal_offences',
        'health_problems',
        'englishProficiency',
        'adminExperience',
        'reason_joining',
        'is_complete'
    ];

    protected $casts = [
        'education' => 'array',
    ];
}